package com.example.straffic.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class SchemaInit implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    @Override
    public void run(String... args) throws Exception {
        // Check if page_view_history table exists
        Integer count = jdbcTemplate.queryForObject(
            "SELECT count(*) FROM user_tables WHERE table_name = 'PAGE_VIEW_HISTORY'", Integer.class);
        
        if (count != null && count == 0) {
            System.out.println("Creating table PAGE_VIEW_HISTORY...");
            try {
                // Try Oracle 12c+ syntax first
                jdbcTemplate.execute("""
                    CREATE TABLE page_view_history (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        page_name VARCHAR2(255) NOT NULL,
                        viewed_at TIMESTAMP NOT NULL
                    )
                """);
                System.out.println("Table PAGE_VIEW_HISTORY created (12c+ syntax).");
            } catch (Exception e) {
                System.out.println("Failed to create table with IDENTITY. Trying 11g syntax...");
                try {
                    // Fallback for Oracle 11g
                    jdbcTemplate.execute("""
                        CREATE TABLE page_view_history (
                            id NUMBER PRIMARY KEY,
                            page_name VARCHAR2(255) NOT NULL,
                            viewed_at TIMESTAMP NOT NULL
                        )
                    """);
                    
                    // Check if sequence exists
                    Integer seqCount = jdbcTemplate.queryForObject(
                        "SELECT count(*) FROM user_sequences WHERE sequence_name = 'PAGE_VIEW_HISTORY_SEQ'", Integer.class);
                    if (seqCount != null && seqCount == 0) {
                        jdbcTemplate.execute("CREATE SEQUENCE page_view_history_seq START WITH 1 INCREMENT BY 1");
                    }

                    jdbcTemplate.execute("""
                        CREATE OR REPLACE TRIGGER page_view_history_trig
                        BEFORE INSERT ON page_view_history
                        FOR EACH ROW
                        BEGIN
                            SELECT page_view_history_seq.NEXTVAL INTO :new.id FROM dual;
                        END;
                    """);
                    System.out.println("Table PAGE_VIEW_HISTORY created (11g syntax).");
                } catch (Exception ex) {
                    System.err.println("Failed to create table PAGE_VIEW_HISTORY: " + ex.getMessage());
                }
            }
        }
    }
}
